name: Deploy FRONTEND to MonsterASP.NET
on: [push]

jobs:
  build_and_deploy_frontend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install dependencies
        run: dotnet restore ./EventPlatform/EventPlatform.csproj --runtime win-x86
        
      - name: Build
        run: dotnet build ./EventPlatform/EventPlatform.csproj --configuration Release --runtime win-x86 --no-restore

      - name: Publish
        run: dotnet publish ./EventPlatform/EventPlatform.csproj --configuration Release --output publish_fe --runtime win-x86 --no-build

      - name: Check publish directory
        run: dir publish_fe

      - name: Deploy Frontend to MonsterASP.NET
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.FE_WEBSITE_NAME }}
          server-computer-name: ${{ secrets.FE_SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.FE_SERVER_USERNAME }}
          server-password: ${{ secrets.FE_SERVER_PASSWORD }}
          source-path: publish_fe
